server:
  port: 8089

spring:

  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        multiTenancy: SCHEMA
    show-sql: true

  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000
  run-tenants-migrations: ${APP_RUN_TENANT_MIGRATIONS:false}

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}
    eureka-service-url-poll-interval-seconds: 300
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.security: DEBUG
    com.user-service: DEBUG
