server:
  port: 8082

spring:
  application:
    name: hello-service

logging:
  pattern:
    console: "%d{HH:mm:ss} [%X{correlationId}] %-5level %logger - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/