spring:
  application:
    name: customer

  datasource:
    url: jdbc:postgresql://localhost:5435/customerdb
    username: joao
    password: joaodev

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

