services:

  postgres-notification:
    image: postgres:17
    container_name: postgres-notifications
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: joaodev
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:

    image: confluentinc/cp-kafka:7.6.1

    container_name: kafka

    depends_on:

      - zookeeper

    ports:

      - "9092:9092"

      - "29092:29092"

    environment:

      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    networks:
      - backend

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

    networks:
      - backend

  notification-service:
    build: .
    container_name: notification-service

    depends_on:
      - kafka
      - postgres-notification

    ports:
      - "8086:8080"

    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-notification:5432/notificationdb
      SPRING_DATASOURCE_USERNAME: joao
      SPRING_DATASOURCE_PASSWORD: joaodev

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: