name: develop

concurrency: development

on:
  workflow_dispatch:

  push:
    branches:
      - development
    paths:
      - 'services/register-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'services/register-service/**'
jobs:
  deployment:
    defaults:
      run:
        working-directory: services/register-service
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: customerdb
          POSTGRES_USER: joao
          POSTGRES_PASSWORD: joaodev
        ports:
          - 5432:5432

        options: >-
          --health-cmd "pg_isready -U joao -d customerdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    environment: development
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Setup Gradlew
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3

      - name: Check Java
        run: java --version

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Check gradlew
        run: ./gradlew --version

      - name: Build gradlew
        env:
          EUREKA_CLIENT_ENABLED: false
          EUREKA_REGISTER_WITH_EUREKA: false
          EUREKA_FETCH_REGISTRY: false
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/customerdb
          SPRING_DATASOURCE_USERNAME: joao
          SPRING_DATASOURCE_PASSWORD: joaodev
        run: ./gradlew build

